### ISSUE TITLE
windows classic theme

### ISSUE THREAD

**Issue by BKSpurgeon** [brandly/elm-minesweeper#12]
As promised:

https://github.com/AlexBSoft/win95.css

Unsure how promising it might be: might not be worth the effort.

rgds
Ben

**Comment by brandly** [comment]
here's a windows 98 option that looks pretty nice: https://jdan.github.io/98.css/

**Comment by BKSpurgeon** [comment]
looks promising very...............might be worth a shot; I'll have a play around with this one..........

**Comment by BKSpurgeon** [comment]
I have applied the changes to the window - (this is a work in progress): styling still needs to be applied to the radio buttons. 

But having seen the initial results: here are my thoughts: the styling is already quite adequate - i don't know how much better it will be with the win 98 styles applied: is it worth pursuing? [(Law of diminishing returns)?](https://en.wikipedia.org/wiki/Diminishing_returns). What are your thoughts on this? We may both get a better return elsewhere?

![image](https://user-images.githubusercontent.com/15097447/80159855-62e49380-860f-11ea-8312-7c3f93725183.png)

**Comment by brandly** [comment]
nice!

i'm kinda interested in checking out 98.css because jdan does really nice work. i like having issues like this around, in case i'm in the mood to toy with something, but i wouldn't worry about it. you'll get more out of writing Elm than just adding CSS classes!

**Comment by BKSpurgeon** [comment]
> i'm kinda interested in checking out 98.css because jdan does really nice work. i like having issues like this around, in case i'm in the mood to toy with something, but i wouldn't worry about it. you'll get more out of writing Elm than just adding CSS classes!

ok. if i'm reading the above correctly, i will abandon the styling.

**Comment by brandly** [comment]
here's one for XP! https://github.com/botoxparty/XP.css

**Comment by brandly** [comment]
just dumping windows-related resources here now, but here's windows 98 running in the browser lol https://copy.sh/v86/?profile=windows98
