### ISSUE TITLE
negative bomb counts render as positive number

### ISSUE THREAD

**Issue by brandly** [brandly/elm-minesweeper#3]
if you place more flags than there are bombs, the bomb count in the corner should display like 
```
0-2
``` 
instead, it displays `002`

**Comment by BKSpurgeon** [comment]
Does this require a change in UI? Perhaps a change in colour or an added + Or - symbol ?

**Comment by brandly** [comment]
i think we just want a `-` added when it's negative. i found a screenshot.

![a screenshot](https://www.mpug.com/wp-content/uploads/2007/05/Full_Flagged_Minesweeper2.png).
