### ISSUE TITLE
managing states for a custom grid layout

### ISSUE THREAD

**Issue by BKSpurgeon** [brandly/elm-minesweeper#9]
Presumably with a Custom grid of something like:

`Custom Int Int Int`

The user will have to enter them into a field/text box, one at a time.

I am proposing that we have a `WorkInProgressCustom Int Int Int` that is used to constantly update the model, and when the model is ready (without any validation problems) then we handle it with the proper `Custom Int Int Int` which represents the final state from which the game can be played.

Was wondering your opinion on how this can be structured?

```elm
-- this is the model:
type alias Model =
    { grid : Grid
    , activeCell : Maybe Cell
    , pressingFace : Bool
    , game : Difficulty
    , time : Int
    , mode : GameMode
    , isRightClicked : Bool
    , menu : Maybe Menu
    }

type Difficulty
    = Beginner
    | Intermediate
    | Expert
    | Custom Int Int Int
    | WorkInProgressCustom Int Int Int
```

When the user updates the fields, then update the WIPCustom type. When the WIPCustom type is all good, then we start the game.

What do you think about that approach?

**Comment by brandly** [comment]
`Difficulty` is used throughout the app to represent a game difficulty. when we receive a value of type `Difficulty`, we always want it to represent a valid difficulty level. 

elm's `case` statements are exhaustive which helps keep us from forgetting to handle some situation. for this reason (among others), we generally want our types to be as large as needed but no larger.

this new `WorkInProgressCustom` constructor is of type

```elm
Int -> Int -> Int -> Difficulty
```

we feed it any three `Int`s to construct a custom `Difficulty`. this type signature matches `Custom`, so it doesn't really give us anything new. anything you store in `WorkInProgressCustom` could already be stored in `Custom`.

---

when we're choosing a custom difficulty, we're viewing the menu. currently, `Menu` is defined as such.

https://github.com/brandly/elm-minesweeper/blob/274c10246481cd97eb1da0369431d1ea0a364cc6/src/Main.elm#L46-L47

it has only one constructor, `DifficultyMenu`. let's extend this constructor to contain the additional values we need for construction a custom difficulty.

```elm
type Menu
  = DifficultyMenu Int Int Int
```

now, these "in progress" values are more accurately tracked as part of the `Menu`. this allows `Difficulty` to stay as-is. we'll use these three `Int`s to construct a `Difficulty` via the `Custom` constructor once those values are chosen and the user finalizes their decision.
